//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string fk_Category { get; set; }
        public bool Status { get; set; }
        public string fk_Unit { get; set; }
    }
}
